library(tximport)
library(biomaRt)

# manage directories and file paths
source('global_variables.R')

# Function to get phenoData df. 
# splits into 4 dataframes for t47d and mcf7 cells and for bulk and single cell
get_pheno_data = function(){
  
  # read pheno data into R
  pd_mcf7 = read.csv(MCF7_RUN_TABLE, sep = '\t')
  pd_t47d = read.csv(T47D_RUN_TABLE, sep = '\t')
  
  # get list of folders containing quants
  mcf7_quant_folders = Sys.glob(file.path(MCF7_QUANTS, 'SRR*'))
  t47d_quant_folders = Sys.glob(file.path(T47D_QUANTS, 'SRR*'))
  
  # get list of accessions from quant_folders (i.e. the last part of file path)
  mcf7_accessions = unlist(lapply(mcf7_quant_folders, basename))
  t47d_accessions = unlist(lapply(t47d_quant_folders, basename))
  
  # get list of quant files 
  mcf7_quant_files = Sys.glob(file.path(MCF7_QUANTS, '*/quant.sf' ))
  t47d_quant_files = Sys.glob(file.path(T47D_QUANTS, '*/quant.sf' ))

  mcf7_df = data.frame(mcf7_accession=mcf7_accessions, quant_file=mcf7_quant_files)
  t47d_df = data.frame(t47d_accession=t47d_accessions, quant_file=t47d_quant_files)
  
  pd_mcf7 = merge(pd_mcf7, mcf7_df, by.x = 'Run', by.y = 'mcf7_accession')
  pd_t47d = merge(pd_t47d, t47d_df, by.x = 'Run', by.y = 't47d_accession')
  
  rownames(pd_mcf7) = pd_mcf7$Run
  rownames(pd_t47d) = pd_t47d$Run
  
  pd_mcf7.bulk = pd_mcf7[rownames(pd_mcf7) %in% MCF7_BULK_DATA_IDS,]
  pd_mcf7.single_cell = pd_mcf7[!(rownames(pd_mcf7) %in% MCF7_BULK_DATA_IDS), ]  
  pd_t47d.bulk = pd_t47d[rownames(pd_t47d) %in% T47D_BULK_DATA_IDS,]
  pd_t47d.single_cell = pd_t47d[!(rownames(pd_t47d) %in% T47D_BULK_DATA_IDS), ]  
  
  pd_mcf7.bulk['time'] = unlist(lapply(as.character(pd_mcf7.bulk['Library_Name']), FUN = function(x) strsplit(x, '_')[[1]][2]))
  # print(pd_mcf7.bulk['Library_Name'])
  mcf7_bulk_labels = lapply(as.character(pd_mcf7.bulk[,'Library_Name']), FUN = function(x) strsplit(x, '_')[[1]])
  pd_mcf7.bulk['condition'] = unlist(lapply(mcf7_bulk_labels, FUN = function(x) x[3]))
  pd_mcf7.bulk['time'] = unlist(lapply(mcf7_bulk_labels, FUN = function(x) strsplit(x[2], 'M')))
  pd_mcf7.bulk['cell_id'] = unlist(lapply(mcf7_bulk_labels, FUN = function(x) x[1]))
  
  t47d_bulk_labels = lapply(as.character(pd_t47d.bulk[,'Library_Name']), FUN = function(x) strsplit(x, '_')[[1]])
  pd_t47d.bulk['condition'] = unlist(lapply(t47d_bulk_labels, FUN = function(x) x[3]))
  pd_t47d.bulk['time'] = unlist(lapply(t47d_bulk_labels, FUN = function(x) strsplit(x[2], 'h')))
  pd_t47d.bulk['cell_id'] = unlist(lapply(t47d_bulk_labels, FUN = function(x) x[1]))
  
  mcf7_single_cell_labels = lapply(as.character(pd_mcf7.single_cell$Library_Name), FUN = function(x) strsplit(x, '_')[[1]])
  pd_mcf7.single_cell['cell_id'] = unlist(lapply(mcf7_single_cell_labels, FUN = function(x) x[1]))
  pd_mcf7.single_cell['time'] = unlist(lapply(mcf7_single_cell_labels, FUN = function(x) strsplit(x[2], 'h')))
  
  t47d_single_cell_labels = lapply(as.character(pd_t47d.single_cell$Library_Name), FUN = function(x) strsplit(x, '_')[[1]])
  pd_t47d.single_cell['cell_id'] = unlist(lapply(t47d_single_cell_labels, FUN = function(x) x[1]))
  pd_t47d.single_cell['time'] = unlist(lapply(t47d_single_cell_labels, FUN = function(x) strsplit(x[2], 'h')))
  
  pd_mcf7.bulk['time'] = as.numeric(pd_mcf7.bulk[,'time'])
  pd_t47d.bulk['time'] = as.numeric(pd_t47d.bulk[,'time'])
  pd_mcf7.single_cell['time'] = as.numeric(pd_mcf7.single_cell[,'time'])
  pd_t47d.single_cell['time'] = as.numeric(pd_t47d.single_cell[,'time'])
  #print(pd_t47d.bulk)
  
  return(list(pd_mcf7.bulk = pd_mcf7.bulk, 
              pd_mcf7.single_cell = pd_mcf7.single_cell, 
              pd_t47d.bulk = pd_t47d.bulk, 
              pd_t47d.single_cell = pd_t47d.single_cell))
}
#pd = get_pheno_data()


#get annotation
get_annotation = function(ensemble_ids, annotation_file, overwrite=F){
  ensemble_ids_no_dot = gsub("\\.[0-9]$", "", ensemble_ids)
  
  if ( file.exists(annotation_file) & !overwrite){
    annot = readRDS(annotation_file)
    message('Local copy of annotation dataframe has been found. Using this. If 
            you do not want to use the local copy, set "from_file" to FALSE')
  } else {
    mart <- useMart("ensembl", dataset = 'hsapiens_gene_ensembl', 
                    host = "www.ensembl.org")
    annot <- getBM(
      mart=mart,
      attributes=c("ensembl_transcript_id", "ensembl_gene_id", "hgnc_symbol", 'entrezgene', 'external_gene_name'),
      values=ensemble_ids_no_dot)
    saveRDS(annot, file = annotation_file)
  }
    return(annot)
}

# read data using tximport. 
# args
# -----
# - pd:     phenoData dataframe (i.e. SraRunTable), including additional column for path to file containing salmon quant file
# - annot:  Annotation for tximport tx2gene. Generated by `get_annotation` 
read_data = function(pd, annot){
  
  # annot = annot[,c('ensembl_transcript_id', 'ensembl_gene_id')]
  # print(head(annot))
  annot = annot[,c('ensembl_transcript_id', 'external_gene_name')]
  
  files = as.vector(pd[,'quant_file'])
  names(files) = as.vector(pd[,'Run'])
  print(files)
  return (tximport(files = files,
                         type='salmon',
                         ignoreTxVersion = T,
                         tx2gene = annot,
                         txIdCol = 'ensembl_transcript_id',
                         geneIdCol = 'ensembl_gene_id'
                         # countsFromAbundance = 'lengthScaledTPM'
  ))
}
#t47d.bulk = read_data(pd$pd_t47d.bulk, t47d_annot)
#mcf7_data = read_data(pd$pd_mcf7.single_cell, mcf7_annot)


#######################################################################################################

# get pd with correct path to quant files
pd = get_pheno_data()
saveRDS(pd, PHENO_DATA)
pd

names(pd)
# get annotation data
t47d_ensembl_ids = read.csv(as.character(pd$pd_t47d.single_cell$quant_file[1]), sep='\t')[, 'Name']
mcf7_ensembl_ids = read.csv(as.character(pd$pd_mcf7.single_cell$quant_file[1]), sep='\t')[, 'Name']

mcf7_annot = get_annotation(mcf7_ensembl_ids, MCF7_ANNOTATION_DATA_FILE, overwrite=F)
t47d_annot = get_annotation(t47d_ensembl_ids, T47D_ANNOTATION_DATA_FILE, overwrite=F)

# parse single cell data into r
mcf7.single_cell = read_data(pd$pd_mcf7.single_cell, mcf7_annot)
t47d.single_cell = read_data(pd$pd_t47d.single_cell, t47d_annot)
# parse bulk data into r
mcf7.bulk = read_data(pd$pd_mcf7.bulk, mcf7_annot)
t47d.bulk = read_data(pd$pd_t47d.bulk, t47d_annot)

#pd$pd_t47d.bulk

data = list(mcf7.single_cell=mcf7.single_cell, 
            t47d.single_cell=t47d.single_cell)
# save data to rds files
saveRDS(data, file = RDS_FILE )





