library(tximport)
library(biomaRt)


# modifies the pheno data to include the path to the relevant quant files
get_pheno_data = function(){
  
  # get list of folders containing quants
  mcf7_quant_folders = Sys.glob(file.path(MCF7_QUANTS, 'SRR*'))
  t47d_quant_folders = Sys.glob(file.path(T47D_QUANTS, 'SRR*'))
  
  # get list of accessions from quant_folders (i.e. the last part of file path)
  mcf7_accessions = unlist(lapply(mcf7_quant_folders, basename))
  t47d_accessions = unlist(lapply(t47d_quant_folders, basename))
  
  # get list of quant files 
  mcf7_quant_files = Sys.glob(file.path(MCF7_QUANTS, '*/quant.sf' ))
  t47d_quant_files = Sys.glob(file.path(T47D_QUANTS, '*/quant.sf' ))

  mcf7_df = data.frame(mcf7_accession=mcf7_accessions, quant_file=mcf7_quant_files)
  t47d_df = data.frame(t47d_accession=t47d_accessions, quant_file=t47d_quant_files)
  
  pd_mcf7 = merge(PD_MCF7, mcf7_df, by.x = 'Run', by.y = 'mcf7_accession')
  pd_t47d = merge(PD_T47D, t47d_df, by.x = 'Run', by.y = 't47d_accession')
  
  return (list(mcf7=pd_mcf7, t47d=pd_t47d))
}
# pd = get_pheno_data()


#get annotation
get_annotation = function(ensemble_ids, annotation_file, overwrite=F){
  ensemble_ids_no_dot = gsub("\\.[0-9]$", "", ensemble_ids)
  
  if ( file.exists(annotation_file) & !overwrite){
    annot = readRDS(annotation_file)
    message('Local copy of annotation dataframe has been found. Using this. If 
            you do not want to use the local copy, set "from_file" to FALSE')
  } else {
    mart <- useMart("ensembl", dataset = 'hsapiens_gene_ensembl', 
                    host = "www.ensembl.org")
    annot <- getBM(
      mart=mart,
      attributes=c("ensembl_transcript_id", "ensembl_gene_id", "hgnc_symbol", 'entrezgene', 'external_gene_name'),
      values=ensemble_ids_no_dot)
    saveRDS(annot, file = annotation_file)
  }
    return(annot)
}

# read data using tximport. 
# args
# -----
# - pd:     phenoData dataframe (i.e. SraRunTable), including additional column for path to file containing salmon quant file
# - annot:  Annotation for tximport tx2gene. Generated by `get_annotation` 
read_data = function(pd, annot, cell='t47d'){
  
  # annot = annot[,c('ensembl_transcript_id', 'ensembl_gene_id')]
  print(head(annot))
  annot = annot[,c('ensembl_transcript_id', 'external_gene_name')]
  
  files = as.vector(pd[[cell]][, 'quant_file'])
  names(files) = as.vector(pd[[cell]][,'Run'])

  if (cell == 't47d'){
    bulk_ids = T47D_BULK_DATA_IDS
  }  else if (cell == 'mcf7'){
    bulk_ids = MCF7_BULK_DATA_IDS
  } else{
    stop('no can do')
  }
  bulk_files = files[bulk_ids]
  
  single_cell_files = files[setdiff(names(files), bulk_ids)]
  
  message(paste('reading', cell, 'single cell'))
  single_cell = tximport(files = single_cell_files,
                         type='salmon',
                         ignoreTxVersion = T,
                         tx2gene = annot,
                         txIdCol = 'ensembl_transcript_id',
                         geneIdCol = 'ensembl_gene_id',
                         # countsFromAbundance = 'lengthScaledTPM'
  )
  
  message(paste('reading', cell, 'bulk'))
  bulk = tximport(files = bulk_files,
                  type='salmon',
                  ignoreTxVersion = T,
                  tx2gene = annot,
                  importer = readr::read_tsv,
                  # countsFromAbundance = 'lengthScaledTPM'
                  )

  data = list(bulk=bulk, 
              single_cell=single_cell)
  return(data)
}
# t47d_data = read_data(pd, t47d_annot, cell='t47d')


#######################################################################################################
# manage directories and file paths
source('global_variables.R')

# read pheno data into R
PD_MCF7 = read.csv(MCF7_RUN_TABLE, sep = '\t')
PD_T47D = read.csv(T47D_RUN_TABLE, sep = '\t')


# get pd with correct path to quant files
pd = get_pheno_data()

pd[['t47d']]['quant_file']

# get annotation data
t47d_ensembl_ids = read.csv(as.character(pd[['t47d']]['quant_file'][1, ]), sep='\t')[, 'Name']
mcf7_ensembl_ids = read.csv(as.character(pd[['mcf7']]['quant_file'][1, ]), sep='\t')[, 'Name']

mcf7_annot = get_annotation(mcf7_ensembl_ids, MCF7_ANNOTATION_DATA_FILE, overwrite=T)
t47d_annot = get_annotation(t47d_ensembl_ids, T47D_ANNOTATION_DATA_FILE, overwrite=T)

# parse the data into r
mcf7_data = read_data(pd, t47d_annot, cell='mcf7')
t47d_data = read_data(pd, mcf7_annot, cell='t47d')

data = list(mcf7=mcf7_data, 
            t47d=t47d_data)
# save data to rds files
saveRDS(data, file = RDS_FILE )


